//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_WcfService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BlServiceContract")]
    public interface BlServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_client", ReplyAction="http://tempuri.org/BlServiceContract/add_clientResponse")]
        void add_client(BE.Client cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_client", ReplyAction="http://tempuri.org/BlServiceContract/add_clientResponse")]
        System.Threading.Tasks.Task add_clientAsync(BE.Client cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_client", ReplyAction="http://tempuri.org/BlServiceContract/del_clientResponse")]
        void del_client(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_client", ReplyAction="http://tempuri.org/BlServiceContract/del_clientResponse")]
        System.Threading.Tasks.Task del_clientAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_car", ReplyAction="http://tempuri.org/BlServiceContract/add_carResponse")]
        void add_car(BE.car ca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_car", ReplyAction="http://tempuri.org/BlServiceContract/add_carResponse")]
        System.Threading.Tasks.Task add_carAsync(BE.car ca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_car", ReplyAction="http://tempuri.org/BlServiceContract/del_carResponse")]
        void del_car(int car_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_car", ReplyAction="http://tempuri.org/BlServiceContract/del_carResponse")]
        System.Threading.Tasks.Task del_carAsync(int car_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_rent", ReplyAction="http://tempuri.org/BlServiceContract/add_rentResponse")]
        void add_rent(BE.Renting rent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_rent", ReplyAction="http://tempuri.org/BlServiceContract/add_rentResponse")]
        System.Threading.Tasks.Task add_rentAsync(BE.Renting rent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_rent", ReplyAction="http://tempuri.org/BlServiceContract/del_rentResponse")]
        void del_rent(long rent_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_rent", ReplyAction="http://tempuri.org/BlServiceContract/del_rentResponse")]
        System.Threading.Tasks.Task del_rentAsync(long rent_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_Fault", ReplyAction="http://tempuri.org/BlServiceContract/add_FaultResponse")]
        void add_Fault(BE.Fault fail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_Fault", ReplyAction="http://tempuri.org/BlServiceContract/add_FaultResponse")]
        System.Threading.Tasks.Task add_FaultAsync(BE.Fault fail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_Fault", ReplyAction="http://tempuri.org/BlServiceContract/del_FaultResponse")]
        void del_Fault(int Fault_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/del_Fault", ReplyAction="http://tempuri.org/BlServiceContract/del_FaultResponse")]
        System.Threading.Tasks.Task del_FaultAsync(int Fault_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_Car_fault", ReplyAction="http://tempuri.org/BlServiceContract/add_Car_faultResponse")]
        void add_Car_fault(BE.Car_Fault cf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/add_Car_fault", ReplyAction="http://tempuri.org/BlServiceContract/add_Car_faultResponse")]
        System.Threading.Tasks.Task add_Car_faultAsync(BE.Car_Fault cf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/Del_car_fault", ReplyAction="http://tempuri.org/BlServiceContract/Del_car_faultResponse")]
        void Del_car_fault(int a, int fault_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/Del_car_fault", ReplyAction="http://tempuri.org/BlServiceContract/Del_car_faultResponse")]
        System.Threading.Tasks.Task Del_car_faultAsync(int a, int fault_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/Del_all_car_fault", ReplyAction="http://tempuri.org/BlServiceContract/Del_all_car_faultResponse")]
        void Del_all_car_fault(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/Del_all_car_fault", ReplyAction="http://tempuri.org/BlServiceContract/Del_all_car_faultResponse")]
        System.Threading.Tasks.Task Del_all_car_faultAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_clint_young", ReplyAction="http://tempuri.org/BlServiceContract/is_clint_youngResponse")]
        bool is_clint_young(BE.Client cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_clint_young", ReplyAction="http://tempuri.org/BlServiceContract/is_clint_youngResponse")]
        System.Threading.Tasks.Task<bool> is_clint_youngAsync(BE.Client cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/close_rent", ReplyAction="http://tempuri.org/BlServiceContract/close_rentResponse")]
        void close_rent(long rent_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/close_rent", ReplyAction="http://tempuri.org/BlServiceContract/close_rentResponse")]
        System.Threading.Tasks.Task close_rentAsync(long rent_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/iretur", ReplyAction="http://tempuri.org/BlServiceContract/ireturResponse")]
        System.Collections.Generic.List<BE.Renting> iretur(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/iretur", ReplyAction="http://tempuri.org/BlServiceContract/ireturResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BE.Renting>> ireturAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/sum_rents", ReplyAction="http://tempuri.org/BlServiceContract/sum_rentsResponse")]
        float sum_rents(int id, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/sum_rents", ReplyAction="http://tempuri.org/BlServiceContract/sum_rentsResponse")]
        System.Threading.Tasks.Task<float> sum_rentsAsync(int id, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/car_profits", ReplyAction="http://tempuri.org/BlServiceContract/car_profitsResponse")]
        double car_profits(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/car_profits", ReplyAction="http://tempuri.org/BlServiceContract/car_profitsResponse")]
        System.Threading.Tasks.Task<double> car_profitsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/fault_list_from_bottom", ReplyAction="http://tempuri.org/BlServiceContract/fault_list_from_bottomResponse")]
        System.Collections.Generic.List<BE.fault_type> fault_list_from_bottom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/fault_list_from_bottom", ReplyAction="http://tempuri.org/BlServiceContract/fault_list_from_bottomResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BE.fault_type>> fault_list_from_bottomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_problem", ReplyAction="http://tempuri.org/BlServiceContract/is_problemResponse")]
        bool is_problem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_problem", ReplyAction="http://tempuri.org/BlServiceContract/is_problemResponse")]
        System.Threading.Tasks.Task<bool> is_problemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/total_price", ReplyAction="http://tempuri.org/BlServiceContract/total_priceResponse")]
        float total_price(long rent_numb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/total_price", ReplyAction="http://tempuri.org/BlServiceContract/total_priceResponse")]
        System.Threading.Tasks.Task<float> total_priceAsync(long rent_numb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_client_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_client_existResponse")]
        bool is_client_exist(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_client_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_client_existResponse")]
        System.Threading.Tasks.Task<bool> is_client_existAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_car_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_car_existResponse")]
        bool is_car_exist(int license_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_car_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_car_existResponse")]
        System.Threading.Tasks.Task<bool> is_car_existAsync(int license_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_rent_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_rent_existResponse")]
        bool is_rent_exist(long run_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_rent_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_rent_existResponse")]
        System.Threading.Tasks.Task<bool> is_rent_existAsync(long run_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_fault_code_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_fault_code_existResponse")]
        bool is_fault_code_exist(int fault_coded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/is_fault_code_exist", ReplyAction="http://tempuri.org/BlServiceContract/is_fault_code_existResponse")]
        System.Threading.Tasks.Task<bool> is_fault_code_existAsync(int fault_coded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/get_time_from_last_rent", ReplyAction="http://tempuri.org/BlServiceContract/get_time_from_last_rentResponse")]
        int get_time_from_last_rent(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/get_time_from_last_rent", ReplyAction="http://tempuri.org/BlServiceContract/get_time_from_last_rentResponse")]
        System.Threading.Tasks.Task<int> get_time_from_last_rentAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/can_rent", ReplyAction="http://tempuri.org/BlServiceContract/can_rentResponse")]
        bool can_rent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/can_rent", ReplyAction="http://tempuri.org/BlServiceContract/can_rentResponse")]
        System.Threading.Tasks.Task<bool> can_rentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/return_avilable_cars", ReplyAction="http://tempuri.org/BlServiceContract/return_avilable_carsResponse")]
        System.Collections.Generic.List<BE.car> return_avilable_cars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/return_avilable_cars", ReplyAction="http://tempuri.org/BlServiceContract/return_avilable_carsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BE.car>> return_avilable_carsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfCar", ReplyAction="http://tempuri.org/BlServiceContract/createListOfCarResponse")]
        void createListOfCar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfCar", ReplyAction="http://tempuri.org/BlServiceContract/createListOfCarResponse")]
        System.Threading.Tasks.Task createListOfCarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/update_time_adn_distance", ReplyAction="http://tempuri.org/BlServiceContract/update_time_adn_distanceResponse")]
        void update_time_adn_distance(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/update_time_adn_distance", ReplyAction="http://tempuri.org/BlServiceContract/update_time_adn_distanceResponse")]
        System.Threading.Tasks.Task update_time_adn_distanceAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfRent", ReplyAction="http://tempuri.org/BlServiceContract/createListOfRentResponse")]
        void createListOfRent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfRent", ReplyAction="http://tempuri.org/BlServiceContract/createListOfRentResponse")]
        System.Threading.Tasks.Task createListOfRentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfClient", ReplyAction="http://tempuri.org/BlServiceContract/createListOfClientResponse")]
        void createListOfClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfClient", ReplyAction="http://tempuri.org/BlServiceContract/createListOfClientResponse")]
        System.Threading.Tasks.Task createListOfClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfFault", ReplyAction="http://tempuri.org/BlServiceContract/createListOfFaultResponse")]
        void createListOfFault();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/createListOfFault", ReplyAction="http://tempuri.org/BlServiceContract/createListOfFaultResponse")]
        System.Threading.Tasks.Task createListOfFaultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/select_client", ReplyAction="http://tempuri.org/BlServiceContract/select_clientResponse")]
        System.Collections.Generic.List<BE.Client> select_client(BE.catagory_of_vehicles cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/select_client", ReplyAction="http://tempuri.org/BlServiceContract/select_clientResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BE.Client>> select_clientAsync(BE.catagory_of_vehicles cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/sinun_car", ReplyAction="http://tempuri.org/BlServiceContract/sinun_carResponse")]
        System.Collections.Generic.List<BE.car> sinun_car(BE.gear gi, BE.catagory_of_vehicles cat, int mak, int dor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BlServiceContract/sinun_car", ReplyAction="http://tempuri.org/BlServiceContract/sinun_carResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BE.car>> sinun_carAsync(BE.gear gi, BE.catagory_of_vehicles cat, int mak, int dor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BlServiceContractChannel : BL_WcfService.ServiceReference1.BlServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlServiceContractClient : System.ServiceModel.ClientBase<BL_WcfService.ServiceReference1.BlServiceContract>, BL_WcfService.ServiceReference1.BlServiceContract {
        
        public BlServiceContractClient() {
        }
        
        public BlServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void add_client(BE.Client cli) {
            base.Channel.add_client(cli);
        }
        
        public System.Threading.Tasks.Task add_clientAsync(BE.Client cli) {
            return base.Channel.add_clientAsync(cli);
        }
        
        public void del_client(long id) {
            base.Channel.del_client(id);
        }
        
        public System.Threading.Tasks.Task del_clientAsync(long id) {
            return base.Channel.del_clientAsync(id);
        }
        
        public void add_car(BE.car ca) {
            base.Channel.add_car(ca);
        }
        
        public System.Threading.Tasks.Task add_carAsync(BE.car ca) {
            return base.Channel.add_carAsync(ca);
        }
        
        public void del_car(int car_number) {
            base.Channel.del_car(car_number);
        }
        
        public System.Threading.Tasks.Task del_carAsync(int car_number) {
            return base.Channel.del_carAsync(car_number);
        }
        
        public void add_rent(BE.Renting rent) {
            base.Channel.add_rent(rent);
        }
        
        public System.Threading.Tasks.Task add_rentAsync(BE.Renting rent) {
            return base.Channel.add_rentAsync(rent);
        }
        
        public void del_rent(long rent_code) {
            base.Channel.del_rent(rent_code);
        }
        
        public System.Threading.Tasks.Task del_rentAsync(long rent_code) {
            return base.Channel.del_rentAsync(rent_code);
        }
        
        public void add_Fault(BE.Fault fail) {
            base.Channel.add_Fault(fail);
        }
        
        public System.Threading.Tasks.Task add_FaultAsync(BE.Fault fail) {
            return base.Channel.add_FaultAsync(fail);
        }
        
        public void del_Fault(int Fault_number) {
            base.Channel.del_Fault(Fault_number);
        }
        
        public System.Threading.Tasks.Task del_FaultAsync(int Fault_number) {
            return base.Channel.del_FaultAsync(Fault_number);
        }
        
        public void add_Car_fault(BE.Car_Fault cf) {
            base.Channel.add_Car_fault(cf);
        }
        
        public System.Threading.Tasks.Task add_Car_faultAsync(BE.Car_Fault cf) {
            return base.Channel.add_Car_faultAsync(cf);
        }
        
        public void Del_car_fault(int a, int fault_id) {
            base.Channel.Del_car_fault(a, fault_id);
        }
        
        public System.Threading.Tasks.Task Del_car_faultAsync(int a, int fault_id) {
            return base.Channel.Del_car_faultAsync(a, fault_id);
        }
        
        public void Del_all_car_fault(int a) {
            base.Channel.Del_all_car_fault(a);
        }
        
        public System.Threading.Tasks.Task Del_all_car_faultAsync(int a) {
            return base.Channel.Del_all_car_faultAsync(a);
        }
        
        public bool is_clint_young(BE.Client cli) {
            return base.Channel.is_clint_young(cli);
        }
        
        public System.Threading.Tasks.Task<bool> is_clint_youngAsync(BE.Client cli) {
            return base.Channel.is_clint_youngAsync(cli);
        }
        
        public void close_rent(long rent_code) {
            base.Channel.close_rent(rent_code);
        }
        
        public System.Threading.Tasks.Task close_rentAsync(long rent_code) {
            return base.Channel.close_rentAsync(rent_code);
        }
        
        public System.Collections.Generic.List<BE.Renting> iretur(long id) {
            return base.Channel.iretur(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BE.Renting>> ireturAsync(long id) {
            return base.Channel.ireturAsync(id);
        }
        
        public float sum_rents(int id, System.DateTime start, System.DateTime end) {
            return base.Channel.sum_rents(id, start, end);
        }
        
        public System.Threading.Tasks.Task<float> sum_rentsAsync(int id, System.DateTime start, System.DateTime end) {
            return base.Channel.sum_rentsAsync(id, start, end);
        }
        
        public double car_profits(int id) {
            return base.Channel.car_profits(id);
        }
        
        public System.Threading.Tasks.Task<double> car_profitsAsync(int id) {
            return base.Channel.car_profitsAsync(id);
        }
        
        public System.Collections.Generic.List<BE.fault_type> fault_list_from_bottom() {
            return base.Channel.fault_list_from_bottom();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BE.fault_type>> fault_list_from_bottomAsync() {
            return base.Channel.fault_list_from_bottomAsync();
        }
        
        public bool is_problem(int id) {
            return base.Channel.is_problem(id);
        }
        
        public System.Threading.Tasks.Task<bool> is_problemAsync(int id) {
            return base.Channel.is_problemAsync(id);
        }
        
        public float total_price(long rent_numb) {
            return base.Channel.total_price(rent_numb);
        }
        
        public System.Threading.Tasks.Task<float> total_priceAsync(long rent_numb) {
            return base.Channel.total_priceAsync(rent_numb);
        }
        
        public bool is_client_exist(long id) {
            return base.Channel.is_client_exist(id);
        }
        
        public System.Threading.Tasks.Task<bool> is_client_existAsync(long id) {
            return base.Channel.is_client_existAsync(id);
        }
        
        public bool is_car_exist(int license_number) {
            return base.Channel.is_car_exist(license_number);
        }
        
        public System.Threading.Tasks.Task<bool> is_car_existAsync(int license_number) {
            return base.Channel.is_car_existAsync(license_number);
        }
        
        public bool is_rent_exist(long run_code) {
            return base.Channel.is_rent_exist(run_code);
        }
        
        public System.Threading.Tasks.Task<bool> is_rent_existAsync(long run_code) {
            return base.Channel.is_rent_existAsync(run_code);
        }
        
        public bool is_fault_code_exist(int fault_coded) {
            return base.Channel.is_fault_code_exist(fault_coded);
        }
        
        public System.Threading.Tasks.Task<bool> is_fault_code_existAsync(int fault_coded) {
            return base.Channel.is_fault_code_existAsync(fault_coded);
        }
        
        public int get_time_from_last_rent(long id) {
            return base.Channel.get_time_from_last_rent(id);
        }
        
        public System.Threading.Tasks.Task<int> get_time_from_last_rentAsync(long id) {
            return base.Channel.get_time_from_last_rentAsync(id);
        }
        
        public bool can_rent() {
            return base.Channel.can_rent();
        }
        
        public System.Threading.Tasks.Task<bool> can_rentAsync() {
            return base.Channel.can_rentAsync();
        }
        
        public System.Collections.Generic.List<BE.car> return_avilable_cars() {
            return base.Channel.return_avilable_cars();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BE.car>> return_avilable_carsAsync() {
            return base.Channel.return_avilable_carsAsync();
        }
        
        public void createListOfCar() {
            base.Channel.createListOfCar();
        }
        
        public System.Threading.Tasks.Task createListOfCarAsync() {
            return base.Channel.createListOfCarAsync();
        }
        
        public void update_time_adn_distance(long id) {
            base.Channel.update_time_adn_distance(id);
        }
        
        public System.Threading.Tasks.Task update_time_adn_distanceAsync(long id) {
            return base.Channel.update_time_adn_distanceAsync(id);
        }
        
        public void createListOfRent() {
            base.Channel.createListOfRent();
        }
        
        public System.Threading.Tasks.Task createListOfRentAsync() {
            return base.Channel.createListOfRentAsync();
        }
        
        public void createListOfClient() {
            base.Channel.createListOfClient();
        }
        
        public System.Threading.Tasks.Task createListOfClientAsync() {
            return base.Channel.createListOfClientAsync();
        }
        
        public void createListOfFault() {
            base.Channel.createListOfFault();
        }
        
        public System.Threading.Tasks.Task createListOfFaultAsync() {
            return base.Channel.createListOfFaultAsync();
        }
        
        public System.Collections.Generic.List<BE.Client> select_client(BE.catagory_of_vehicles cat) {
            return base.Channel.select_client(cat);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BE.Client>> select_clientAsync(BE.catagory_of_vehicles cat) {
            return base.Channel.select_clientAsync(cat);
        }
        
        public System.Collections.Generic.List<BE.car> sinun_car(BE.gear gi, BE.catagory_of_vehicles cat, int mak, int dor) {
            return base.Channel.sinun_car(gi, cat, mak, dor);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BE.car>> sinun_carAsync(BE.gear gi, BE.catagory_of_vehicles cat, int mak, int dor) {
            return base.Channel.sinun_carAsync(gi, cat, mak, dor);
        }
    }
}
